#include <iostream>
using namespace std;
int main ()
{int a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,br=0;
cout << "DSPK, koqto izvejda chetnite chisla" "\n " ;
cout <<"Vyvedete chisloto a: "; cin>>a;
cout <<"Vyvedete chisloto b: "; cin>>b;
cout <<"Vyvedete chisloto c: "; cin>>c;
cout <<"Vyvedete chisloto d: "; cin>>d;
cout <<"Vyvedete chisloto e: "; cin>>e;
cout <<"Vyvedete chisloto f: "; cin>>f;
cout <<"Vyvedete chisloto g: "; cin>>g;
cout <<"Vyvedete chisloto h: "; cin>>h;
cout <<"Vyvedete chisloto i: "; cin>>i;
cout <<"Vyvedete chisloto j: "; cin>>j;
cout <<"Vyvedete chisloto k: "; cin>>k;
cout <<"Vyvedete chisloto l: "; cin>>l;
cout <<"Vyvedete chisloto m: "; cin>>m;
cout <<"Vyvedete chisloto n: "; cin>>n;
cout <<"Vyvedete chisloto o: "; cin>>o;
cout <<"Vyvedete chisloto p: "; cin>>p;
cout <<"Vyvedete chisloto q: "; cin>>q;
cout <<"Vyvedete chisloto r: "; cin>>r;
cout <<"Vyvedete chisloto s: "; cin>>s;
cout <<"Vyvedete chisloto t: "; cin>>t;
cout <<"Vyvedete chisloto u: "; cin>>u;
cout <<"Vyvedete chisloto v: "; cin>>v;
cout <<"Vyvedete chisloto w: "; cin>>w;
cout <<"Vyvedete chisloto x: "; cin>>x;
cout <<"Vyvedete chisloto y: "; cin>>y;
cout <<"Vyvedete chisloto z: "; cin>>z;
if (a % 2 ==0) br=br+1;
if (b % 2 ==0) br=br+1;
if (c % 2 ==0) br=br+1;
if (d % 2 ==0) br=br+1;
if (e % 2 ==0) br=br+1;
if (f % 2 ==0) br=br+1;
if (g % 2 ==0) br=br+1;
if (h % 2 ==0) br=br+1;
if (i % 2 ==0) br=br+1;
if (j % 2 ==0) br=br+1;
if (k % 2 ==0) br=br+1;
if (l % 2 ==0) br=br+1;
if (m % 2 ==0) br=br+1;
if (n % 2 ==0) br=br+1;
if (o % 2 ==0) br=br+1;
if (p % 2 ==0) br=br+1;
if (q % 2 ==0) br=br+1;
if (r % 2 ==0) br=br+1;
if (s % 2 ==0) br=br+1;
if (t % 2 ==0) br=br+1;
if (u % 2 ==0) br=br+1;
if (v % 2 ==0) br=br+1;
if (w % 2 ==0) br=br+1;
if (x % 2 ==0) br=br+1;
if (y % 2 ==0) br=br+1;
if (z % 2 ==0) br=br+1;
cout << "Broq na chetnite chisla e "<< br<< endl;
system ("pause");
return 0;
}
